---
# GitHub Repository Settings
# This file configures repository settings via the GitHub Settings app
# https://github.com/apps/settings

repository:
  # Repository basic settings
  name: "ansible.role.prep"
  description: "Ansible Role for preparing Troposphere/CloudFormation deployment Workflows"
  homepage: ""
  topics:
    - template
    - ansible
    - role
    - splendidcube

  # Repository features
  private: true
  is_template: false
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: false

  # Repository settings
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: master
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false

      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts: []

      # Restrictions
      enforce_admins: false
      allow_force_pushes: false
      allow_deletions: false

      # Additional settings
      block_creations: false
      require_conversation_resolution: true

  - name: development
    protection:
      # Less strict protection for development branch
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        require_last_push_approval: false

      # Require status checks to pass before merging
      required_status_checks:
        strict: false
        contexts: []

      # Restrictions
      enforce_admins: false
      allow_force_pushes: true
      allow_deletions: false

      # Additional settings
      block_creations: false
      require_conversation_resolution: false
