---
# Pre-commit configuration for SplendidCube projects
# See https://pre-commit.com for more information

repos:
  # Python code quality (using Ruff for speed and consolidation)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [--fix]
        name: ruff-lint-fix
      - id: ruff-format
        name: ruff-format

  # Rust code quality
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: rust-fmt
      - id: cargo-check
        name: rust-cargo-check
      - id: clippy
        name: rust-clippy
        args: [--all-targets, --all-features]

  # JavaScript/TypeScript/Vue.js code quality
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.33.0
    hooks:
      - id: eslint
        name: eslint-js-ts-vue
        files: \.(js|ts|vue)$
        additional_dependencies:
          - eslint@9.15.0
          - eslint-plugin-vue@9.30.0
          - "@typescript-eslint/eslint-plugin@8.15.0"
          - "@typescript-eslint/parser@8.15.0"

  # Prettier for JavaScript/TypeScript/Vue/CSS/HTML/YAML (non-Ansible)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-js-ts-vue-css-html-yaml
        files: \.(js|ts|vue|css|scss|html|json|ya?ml)$
        exclude: ^(tasks|handlers|vars|defaults|meta|playbooks?|site\.ya?ml|.*playbook.*\.ya?ml|inventory.*\.ya?ml|group_vars|host_vars)/.*\.ya?ml$
        additional_dependencies:
          - prettier@3.3.3

  # Ansible linting
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.8.1
    hooks:
      - id: ansible-lint
        name: ansible-lint
        files: ^(tasks|handlers|vars|defaults|meta|playbooks?|site\.ya?ml|.*playbook.*\.ya?ml|inventory.*\.ya?ml|group_vars|host_vars)/.*\.ya?ml$|^.*\.(yml|yaml)$
        exclude: ^(\.github|docs|tests)/.*\.ya?ml$
        args: [--fix]
        additional_dependencies:
          - ansible-core>=2.12.0

  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        name: hadolint-dockerfile
        files: Dockerfile.*

  # Markdown formatting and linting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: mdformat-fix
        additional_dependencies:
          - mdformat-gfm # GitHub Flavored Markdown
          - mdformat-frontmatter # YAML frontmatter support
          - mdformat-myst # MyST syntax support for Sphinx

  # General file formatting and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trim-trailing-whitespace
      - id: end-of-file-fixer
        name: ensure-newline-eof
      - id: check-yaml
        name: check-yaml-syntax
      - id: check-json
        name: check-json-syntax
      - id: check-toml
        name: check-toml-syntax
      - id: check-merge-conflict
        name: check-merge-conflicts
      - id: check-added-large-files
        name: check-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
        name: check-case-conflicts
      - id: check-executables-have-shebangs
        name: check-executables-shebangs
      - id: mixed-line-ending
        name: check-line-endings

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # Conventional commits validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        name: conventional-commits
        stages: [commit-msg]
        args:
          - "--strict"
          - "--types=feat,fix,docs,style,refactor,test,chore,ci,build,perf,revert"
          - "--scopes-regex=^[a-z0-9-]+$"
          - "--subject-regex=^:[a-z0-9_+-]+: [a-z].*$"

# Configuration for specific tools
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
